name: Deploy to ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_IAM }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY_IAM }}
          aws-region: us-east-1

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster sovereign-node-cluster --service sovereign-node-service --force-new-deployment
